In [1]:
from pyclassrich.gnps import Proteosafe
import matplotlib.pyplot as plt

from pyclassrich.models import class_enrichment, impact_plot, ont_graph, get_ont_graph
from pyclassrich.utils import *
import pandas as pd
import json

%matplotlib

Using matplotlib backend: TkAgg

In [2]:
params = {
    "mzmine": False,
    "mzmine_batch": False,
    "desc": 'description',
    "gnps_taskid": 'f8e21bcb454849bbb74eb09f2bb8cb2a',
    "gnps_nap": False,
    "nap_taskid": '806e59ef9ae9485cb48ed2888d5beab5',
    "classify": True,
    "normalization": {
        "perform": True,
        "type": 'TIC'
    },
    "enrich": True,
    "comparison": {
        "classes": 'Most,Least',
        "field": 'ATTRIBUTE_Most_Least',
        "test": 'ttest',
        "vthr": 0.5
    },
    "summarize": True,
    "pcoa": True,
    "pcoa_metric": 'canberra',
    "pcoa_norm": True,
    "pcoa_scale": True,
    "email": 'email@gmail.com'
}

In [3]:
params.keys()

dict_keys(['mzmine', 'mzmine_batch', 'desc', 'gnps_taskid', 'gnps_nap', 'nap_taskid', 'classify', 'normalization', 'enrich', 'comparison', 'summarize', 'pcoa', 'pcoa_metric', 'pcoa_norm', 'pcoa_scale', 'email'])

In [4]:
params

{'mzmine': False,
 'mzmine_batch': False,
 'desc': 'description',
 'gnps_taskid': 'f8e21bcb454849bbb74eb09f2bb8cb2a',
 'gnps_nap': False,
 'nap_taskid': '806e59ef9ae9485cb48ed2888d5beab5',
 'classify': True,
 'normalization': {'perform': True, 'type': 'TIC'},
 'enrich': True,
 'comparison': {'classes': 'Most,Least',
  'field': 'ATTRIBUTE_Most_Least',
  'test': 'ttest',
  'vthr': 0.5},
 'summarize': True,
 'pcoa': True,
 'pcoa_metric': 'canberra',
 'pcoa_norm': True,
 'pcoa_scale': True,
 'email': 'email@gmail.com'}

In [5]:
ndict = Proteosafe(params['nap_taskid'], 'NAP')

ndict.get_nap()

ndb =  ndict.ndb
ndb = ndb.replace(' ', '')

ndb

'SUPNAT'

In [6]:
type(ndict)

pyclassrich.gnps.Proteosafe

In [7]:
%%time

annotated = classify(params['nap_taskid'])
annotated.head()

Loading database...
CPU times: user 9.85 s, sys: 1.36 s, total: 11.2 s
Wall time: 12.2 s

,cluster.index,SpectrumID,Smiles,INCHI,Identifier,Score,Ncandidates,InChI,kingdom_name,superclass_name,class_name,subclass_name,superclass_id,class_id,subclass_id,conflict,ginchikey,InchiKey
0,2,CCMSLIB00005738697,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,SN00048579,1,15,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,Organic compounds,Benzenoids,Phenol ethers,Anisoles,CHEMONTID:0002448,CHEMONTID:0002341,CHEMONTID:0000138,no,YVYMBNSKXOXSKW-HXUWFJFHSA-N,YVYMBNSKXOXSKW-HXUWFJFHSA-N
1,2,CCMSLIB00005738697,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,SN00048572,0.978,15,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,Organic compounds,Benzenoids,Phenol ethers,Anisoles,CHEMONTID:0002448,CHEMONTID:0002341,CHEMONTID:0000138,no,YVYMBNSKXOXSKW-HXUWFJFHSA-N,YVYMBNSKXOXSKW-HXUWFJFHSA-N
2,2,CCMSLIB00005738697,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,SN00083755,0.974,15,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,Organic compounds,Benzenoids,Phenol ethers,Anisoles,CHEMONTID:0002448,CHEMONTID:0002341,CHEMONTID:0000138,no,YVYMBNSKXOXSKW-HXUWFJFHSA-N,YVYMBNSKXOXSKW-HXUWFJFHSA-N
3,2,CCMSLIB00005738697,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,SN00048567,0.928,15,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,Organic compounds,Benzenoids,Benzene and substituted derivatives,Methoxybenzenes,CHEMONTID:0002448,CHEMONTID:0002279,CHEMONTID:0004113,no,YVYMBNSKXOXSKW-HXUWFJFHSA-N,YVYMBNSKXOXSKW-HXUWFJFHSA-N
4,3,CCMSLIB00003137012,,,SN00099478,1,8,InChI=1S/C30H41NO4/c1-20(12-13-24-21(2)10-8-15...,Organic compounds,Lipids and lipid-like molecules,Prenol lipids,Sesquiterpenoids,CHEMONTID:0000012,CHEMONTID:0000259,CHEMONTID:0001550,,,MURVJQSDIIPTEC-GTTGMRKWSA-N

In [8]:
annotated.shape

(1558, 18)

In [9]:
gnps = Proteosafe(params['gnps_taskid'], 'FBMN')
gnps.get_gnps()

feat = gnps.feat
meta = gnps.meta

meta.head()

,filename,ATTRIBUTE_sample_type,ATTRIBUTE_hpe,ATTRIBUTE_MOI,ATTRIBUTE_Most_Least
0,Cell-0hpe-1-pooled_P1-A-7_01_7257.mzXML,BtOnly,0,L,-
1,Cell-0hpe-2-pooled_P1-A-8_01_7258.mzXML,BtOnly,0,L,-
2,Cell-0hpe-31-pooled_P1-D-1_01_7287.mzXML,BtOnly,0,H,-
3,Cell-0hpe-32-pooled_P1-D-2_01_7288.mzXML,BtOnly,0,H,-
4,Cell-0hpe-33-pooled_P1-D-3_01_7289.mzXML,BtOnly,0,H,-

In [10]:
from pyclassrich.stats import *

In [11]:
tabgnps = ndict.tabgnps

tabgnps.head()

,cluster.index,number.of.spectra,parent.mass,precursor.charge,precursor.mass,sum.precursor.intensity.,G1,G2,G3,G4,...,RTStdErr,UniqueFileSourcesCount,LibraryID,ProteoSAFeClusterLink,AllGroups,DefaultGroups,EvenOdd,SpectrumID,Smiles,INCHI
0,2,26,454.2925,1,454.2925,1.291700e+08,0,0,0,0,...,0,26,Massbank:RP026103 1-palmitoyl-2-hydroxy-sn-gly...,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,CCMSLIB00005738697,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-12-13-1...
1,3,26,480.3083,1,480.3083,1.534335e+08,0,0,0,0,...,0,26,Spectral Match to 1-(9Z-Octadecenoyl)-sn-glyce...,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,CCMSLIB00003137012,NaN,NaN
2,4,26,494.3239,1,494.3239,7.287906e+07,0,0,0,0,...,0,26,NaN,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,NaN,NaN,NaN
3,5,26,466.2926,1,466.2926,5.508946e+07,0,0,0,0,...,0,26,NaN,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,NaN,NaN,NaN
4,6,26,452.2768,1,452.2768,6.042495e+07,0,0,0,0,...,0,26,NaN,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = univariate(annotated, tabgnps, 
                params, feat, meta)

df.head()

,cluster.index,parent.mass,RTMean,LibraryID,Identifier,InchiKey,kingdom_name,superclass_name,superclass_id,class_name,...,subclass_name,subclass_id,Smiles,InChI,row ID,row m/z,row retention time,fchange,pval,cpval
597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,338.341339,17.766594,1.783147,0.190487,0.333560
0,2.0,454.2925,11.6428,Massbank:RP026103 1-palmitoyl-2-hydroxy-sn-gly...,SN00048579,YVYMBNSKXOXSKW-HXUWFJFHSA-N,Organic compounds,Benzenoids,CHEMONTID:0002448,Phenol ethers,...,Anisoles,CHEMONTID:0000138,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,2,454.292475,11.642782,3.524664,0.003093,0.022670
1,3.0,480.3083,11.9519,Spectral Match to 1-(9Z-Octadecenoyl)-sn-glyce...,SN00099478,MURVJQSDIIPTEC-GTTGMRKWSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Prenol lipids,...,Sesquiterpenoids,CHEMONTID:0001550,,InChI=1S/C30H41NO4/c1-20(12-13-24-21(2)10-8-15...,3,480.308327,11.951862,2.156446,0.009297,0.039368
2,4.0,494.3239,12.6089,NaN,SN00312735,DQZJPKYNSKJWBF-NONLCYDASA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Prenol lipids,...,Diterpenoids,CHEMONTID:0001551,,InChI=1S/C31H43NO4/c1-24(13-9-15-26(3)23-29(33...,4,494.323893,12.608921,86.271250,0.000485,0.007785
3,5.0,466.2926,11.4456,NaN,SN00028323,RDBVGLHGYXTTIF-GEVWXPSMSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Prenol lipids,...,Sesquiterpenoids,CHEMONTID:0001550,,InChI=1S/C25H37F2N3O3/c1-5-28-24(33)30-20-7-9-...,5,466.292625,11.445601,146.257554,0.001940,0.017259

In [13]:
df.columns

Index(['cluster.index', 'parent.mass', 'RTMean', 'LibraryID', 'Identifier',
       'InchiKey', 'kingdom_name', 'superclass_name', 'superclass_id',
       'class_name', 'class_id', 'subclass_name', 'subclass_id', 'Smiles',
       'InChI', 'row ID', 'row m/z', 'row retention time', 'fchange', 'pval',
       'cpval'],
      dtype='object')

In [14]:
chemrich = df.copy().loc[~df['cluster.index'].isnull(),
                         ['Identifier', 'class_name', 'InChI', 
                          'pval', 'fchange']]

chemrich.columns = ['Compound_Name', 'Class', 'InChI', 'pvalue', 'foldchange']

clusterdf = class_enrichment(chemrich, cfield='Class', nfield='Compound_Name')
clusterdf.head()

,name,pvalues,adjustedpvalue,keycpdname,alteredMetabolites,upcount,downcount,upratio,altratio,csize,xlogp
0,Phenol ethers,0.00479489,0.00733336,SN00048579,3,2,1,0.666667,0.750000,4,6.05766
1,Prenol lipids,1.35954e-33,3.5348e-32,SN00163714,50,31,19,0.620000,0.641026,78,4.60680
2,Naphthothiazoles,1.15473e-07,7.50577e-07,SN00007859,3,2,1,0.666667,1.000000,3,1.58140
3,Benzene and substituted derivatives,8.52085e-05,0.000301625,SN00085381,5,2,3,0.400000,0.312500,16,2.89970
4,Carboxylic acids and derivatives,0.000520264,0.00122971,SN00105917,10,7,3,0.700000,0.303030,33,3.48240

In [15]:
pr_lip_loc = df['class_name']=='Prenol lipids'

pr_lip_loc.sum()

78

In [16]:
sum(df.loc[pr_lip_loc, 'pval'] < 0.05)

50

In [17]:
clusterdf.shape

(26, 11)

In [20]:
impact_plot(clusterdf, chemrich, cfield='Class', nfield='Compound_Name',
            scaling_factor=20)

In [21]:
help(impact_plot)

Help on function impact_plot in module pyclassrich.models:

impact_plot(clusterdf, chemrich, cfield='ChemRICHClusters', nfield='CompoundName', scaling_factor=20, top=0, outdir='', filename='', fig_title='')
    Impact plot
    Parameters
    ----------
    chemrich : pd.DataFrame
       Dataframe containing identifiers, classes and statistics
    clusterdf : pd.DataFrame
       Dataframe with enrichment results
    cfield : str
       Column label for chemical class
    nfield : str
       Compound identifiers
    scaling_factor : int
       Compound identifiers
    outdir : str
       Output directory
    filename : str
       file name
    fig_title : str
       Figure title
    Returns
    -------
    impact_plot : pdf

In [22]:
impact_plot(clusterdf, chemrich, cfield='Class', nfield='Compound_Name',
            scaling_factor=20, top=10)

In [23]:
impact_plot(clusterdf, chemrich, cfield='Class', nfield='Compound_Name',
            scaling_factor=20, outdir='.', filename='most_least.pdf',
            fig_title='Most vs Least', top=10)

In [24]:
get_ont_graph(df, params, cfield='Class', nfield='compound names', 
              method='kstest', outdir='.', scaling_factor=10)

In [25]:
# Intern

from pyclassrich.models import Chemont

clfy = Chemont()

clfy.is_directed_acyclic_graph()

True

In [26]:
clfy.descendants('CHEMONTID:0000261')

{'CHEMONTID:0000000', 'CHEMONTID:9999999'}

In [27]:
clfy.ancestors('CHEMONTID:0000261')

{'CHEMONTID:0000029',
 'CHEMONTID:0000059',
 'CHEMONTID:0000064',
 'CHEMONTID:0000142',
 'CHEMONTID:0000145',
 'CHEMONTID:0000147',
 'CHEMONTID:0000149',
 'CHEMONTID:0000161',
 'CHEMONTID:0000181',
 'CHEMONTID:0000202',
 'CHEMONTID:0000238',
 'CHEMONTID:0000253',
 'CHEMONTID:0000334',
 'CHEMONTID:0000336',
 'CHEMONTID:0000337',
 'CHEMONTID:0000354',
 'CHEMONTID:0000356',
 'CHEMONTID:0000358',
 'CHEMONTID:0000379',
 'CHEMONTID:0000465',
 'CHEMONTID:0000476',
 'CHEMONTID:0000494',
 'CHEMONTID:0000507',
 'CHEMONTID:0001111',
 'CHEMONTID:0001136',
 'CHEMONTID:0001138',
 'CHEMONTID:0001304',
 'CHEMONTID:0001331',
 'CHEMONTID:0001361',
 'CHEMONTID:0001362',
 'CHEMONTID:0001389',
 'CHEMONTID:0001391',
 'CHEMONTID:0001532',
 'CHEMONTID:0001533',
 'CHEMONTID:0001536',
 'CHEMONTID:0001583',
 'CHEMONTID:0001584',
 'CHEMONTID:0001586',
 'CHEMONTID:0001587',
 'CHEMONTID:0001594',
 'CHEMONTID:0001607',
 'CHEMONTID:0001608',
 'CHEMONTID:0001612',
 'CHEMONTID:0001614',
 'CHEMONTID:0001615',
 'CHEMONTID:0001630',
 'CHEMONTID:0001631',
 'CHEMONTID:0001632',
 'CHEMONTID:0001633',
 'CHEMONTID:0001645',
 'CHEMONTID:0001649',
 'CHEMONTID:0001710',
 'CHEMONTID:0001711',
 'CHEMONTID:0001712',
 'CHEMONTID:0001737',
 'CHEMONTID:0001738',
 'CHEMONTID:0001739',
 'CHEMONTID:0001741',
 'CHEMONTID:0001742',
 'CHEMONTID:0001743',
 'CHEMONTID:0001758',
 'CHEMONTID:0001759',
 'CHEMONTID:0001761',
 'CHEMONTID:0001787',
 'CHEMONTID:0001788',
 'CHEMONTID:0001800',
 'CHEMONTID:0001802',
 'CHEMONTID:0001803',
 'CHEMONTID:0001808',
 'CHEMONTID:0001817',
 'CHEMONTID:0001827',
 'CHEMONTID:0001828',
 'CHEMONTID:0001890',
 'CHEMONTID:0001900',
 'CHEMONTID:0002106',
 'CHEMONTID:0002355',
 'CHEMONTID:0002503',
 'CHEMONTID:0002504',
 'CHEMONTID:0002505',
 'CHEMONTID:0002506',
 'CHEMONTID:0002507',
 'CHEMONTID:0002508',
 'CHEMONTID:0002523',
 'CHEMONTID:0002551',
 'CHEMONTID:0002568',
 'CHEMONTID:0002569',
 'CHEMONTID:0002580',
 'CHEMONTID:0002581',
 'CHEMONTID:0002582',
 'CHEMONTID:0002583',
 'CHEMONTID:0002585',
 'CHEMONTID:0002586',
 'CHEMONTID:0002587',
 'CHEMONTID:0002588',
 'CHEMONTID:0002589',
 'CHEMONTID:0002590',
 'CHEMONTID:0002591',
 'CHEMONTID:0002592',
 'CHEMONTID:0002593',
 'CHEMONTID:0002594',
 'CHEMONTID:0002595',
 'CHEMONTID:0002596',
 'CHEMONTID:0002597',
 'CHEMONTID:0002598',
 'CHEMONTID:0002599',
 'CHEMONTID:0002600',
 'CHEMONTID:0002601',
 'CHEMONTID:0002602',
 'CHEMONTID:0002603',
 'CHEMONTID:0002604',
 'CHEMONTID:0002605',
 'CHEMONTID:0002606',
 'CHEMONTID:0002612',
 'CHEMONTID:0002614',
 'CHEMONTID:0002615',
 'CHEMONTID:0002616',
 'CHEMONTID:0002617',
 'CHEMONTID:0002642',
 'CHEMONTID:0002643',
 'CHEMONTID:0002644',
 'CHEMONTID:0002650',
 'CHEMONTID:0002651',
 'CHEMONTID:0002652',
 'CHEMONTID:0002682',
 'CHEMONTID:0002683',
 'CHEMONTID:0002684',
 'CHEMONTID:0002685',
 'CHEMONTID:0002686',
 'CHEMONTID:0002687',
 'CHEMONTID:0002689',
 'CHEMONTID:0002690',
 'CHEMONTID:0002708',
 'CHEMONTID:0002709',
 'CHEMONTID:0002710',
 'CHEMONTID:0002711',
 'CHEMONTID:0002712',
 'CHEMONTID:0002713',
 'CHEMONTID:0002714',
 'CHEMONTID:0002715',
 'CHEMONTID:0002716',
 'CHEMONTID:0002754',
 'CHEMONTID:0002810',
 'CHEMONTID:0002819',
 'CHEMONTID:0002820',
 'CHEMONTID:0002821',
 'CHEMONTID:0002830',
 'CHEMONTID:0002831',
 'CHEMONTID:0002832',
 'CHEMONTID:0002833',
 'CHEMONTID:0002896',
 'CHEMONTID:0002897',
 'CHEMONTID:0002898',
 'CHEMONTID:0002900',
 'CHEMONTID:0002901',
 'CHEMONTID:0002902',
 'CHEMONTID:0002907',
 'CHEMONTID:0002908',
 'CHEMONTID:0002909',
 'CHEMONTID:0002914',
 'CHEMONTID:0002915',
 'CHEMONTID:0002934',
 'CHEMONTID:0002935',
 'CHEMONTID:0002988',
 'CHEMONTID:0002989',
 'CHEMONTID:0002990',
 'CHEMONTID:0002991',
 'CHEMONTID:0002992',
 'CHEMONTID:0002993',
 'CHEMONTID:0002994',
 'CHEMONTID:0002996',
 'CHEMONTID:0002997',
 'CHEMONTID:0003002',
 'CHEMONTID:0003003',
 'CHEMONTID:0003004',
 'CHEMONTID:0003005',
 'CHEMONTID:0003006',
 'CHEMONTID:0003012',
 'CHEMONTID:0003013',
 'CHEMONTID:0003190',
 'CHEMONTID:0003191',
 'CHEMONTID:0003405',
 'CHEMONTID:0003406',
 'CHEMONTID:0003407',
 'CHEMONTID:0003415',
 'CHEMONTID:0003465',
 'CHEMONTID:0003466',
 'CHEMONTID:0003467',
 'CHEMONTID:0003470',
 'CHEMONTID:0003471',
 'CHEMONTID:0003472',
 'CHEMONTID:0003473',
 'CHEMONTID:0003474',
 'CHEMONTID:0003475',
 'CHEMONTID:0003478',
 'CHEMONTID:0003479',
 'CHEMONTID:0003480',
 'CHEMONTID:0003484',
 'CHEMONTID:0003485',
 'CHEMONTID:0003486',
 'CHEMONTID:0003496',
 'CHEMONTID:0003501',
 'CHEMONTID:0003502',
 'CHEMONTID:0003503',
 'CHEMONTID:0003504',
 'CHEMONTID:0003505',
 'CHEMONTID:0003506',
 'CHEMONTID:0003507',
 'CHEMONTID:0003508',
 'CHEMONTID:0003509',
 'CHEMONTID:0003510',
 'CHEMONTID:0003511',
 'CHEMONTID:0003512',
 'CHEMONTID:0003513',
 'CHEMONTID:0003514',
 'CHEMONTID:0003515',
 'CHEMONTID:0003516',
 'CHEMONTID:0003520',
 'CHEMONTID:0003523',
 'CHEMONTID:0003524',
 'CHEMONTID:0003525',
 'CHEMONTID:0003526',
 'CHEMONTID:0003527',
 'CHEMONTID:0003528',
 'CHEMONTID:0003530',
 'CHEMONTID:0003531',
 'CHEMONTID:0003532',
 'CHEMONTID:0003533',
 'CHEMONTID:0003534',
 'CHEMONTID:0003535',
 'CHEMONTID:0003540',
 'CHEMONTID:0003541',
 'CHEMONTID:0003542',
 'CHEMONTID:0003551',
 'CHEMONTID:0003552',
 'CHEMONTID:0003553',
 'CHEMONTID:0003554',
 'CHEMONTID:0003555',
 'CHEMONTID:0003556',
 'CHEMONTID:0003579',
 'CHEMONTID:0003580',
 'CHEMONTID:0003587',
 'CHEMONTID:0003588',
 'CHEMONTID:0003637',
 'CHEMONTID:0003638',
 'CHEMONTID:0003639',
 'CHEMONTID:0003640',
 'CHEMONTID:0003641',
 'CHEMONTID:0003642',
 'CHEMONTID:0003643',
 'CHEMONTID:0003644',
 'CHEMONTID:0003645',
 'CHEMONTID:0003646',
 'CHEMONTID:0003647',
 'CHEMONTID:0003648',
 'CHEMONTID:0003649',
 'CHEMONTID:0003650',
 'CHEMONTID:0003651',
 'CHEMONTID:0003652',
 'CHEMONTID:0003678',
 'CHEMONTID:0003679',
 'CHEMONTID:0003680',
 'CHEMONTID:0003681',
 'CHEMONTID:0004154',
 'CHEMONTID:0004181',
 'CHEMONTID:0004182',
 'CHEMONTID:0004510',
 'CHEMONTID:0004559',
 'CHEMONTID:0004561',
 'CHEMONTID:0004785',
 'CHEMONTID:0004818',
 'CHEMONTID:0004821',
 'CHEMONTID:0004828',
 'CHEMONTID:0004829'}

In [28]:
clfy.edges_to_parents('CHEMONTID:0000261')

• Phenylpropanoids and polyketides ⟶ is_a ⟶ Organic compounds

In [29]:
clfy.edges_to_children('CHEMONTID:0000261')

• Phenylpropanoids and polyketides ⟵ is_a ⟵ Cinnamaldehydes
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Macrolactams
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Coumarins and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Macrolides and analogues
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Tetracyclines
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Tannins
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Stilbenes
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Flavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Cinnamic acids and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Brevetoxins and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Neoflavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Aurone flavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Depsides and depsidones
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Isochromanequinones
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Kavalactones
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Ochratoxins and related substances
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Saxitoxins, gonyautoxins, and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Okadaic acids and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Ciguatera toxins
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Sterigmatocystins
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Isocoumarins and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Macrolide lactams
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Anthracyclines
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Isoflavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Homoisoflavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Phenylpropanoic acids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Alpha-methyldeoxybenzoin flavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ 3,4-dihydrocoumarins
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Diarylheptanoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Cinnamyl alcohols
• Phenylpropanoids and polyketides ⟵ is_a ⟵ 1,2-diaryl-2-propen-1-ols
• Phenylpropanoids and polyketides ⟵ is_a ⟵ 2-arylbenzofuran flavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Angucyclines
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Linear 1,3-diarylpropanoids

In [30]:
params = {
    "mzmine": False,
    "mzmine_batch": False,
    "desc": 'description',
    "gnps_taskid": 'e3b521658618404a822b238992d70955',
    "gnps_nap": False,
    "nap_taskid": '95eb5494f76940f3a8c044a1e8a666f0',
    "classify": True,
    "normalization": {
        "perform": True,
        "type": 'TIC'
    },
    "enrich": True,
    "comparison": {
        "classes": 'all',
        "field": 'ATTRIBUTE_State',
        "test": 'anova',
        "vthr": 0.5
    },
    "summarize": True,
    "pcoa": True,
    "pcoa_metric": 'canberra',
    "pcoa_norm": True,
    "pcoa_scale": True,
    "email": 'email@gmail.com'
}

In [31]:
gnps = Proteosafe(params['gnps_taskid'], 'FBMN')
gnps.get_gnps()

feat = gnps.feat
meta = gnps.meta

meta.head()

,filename,ATTRIBUTE_SampleNumber,ATTRIBUTE_Subfamily,ATTRIBUTE_Genre,ATTRIBUTE_Specie,ATTRIBUTE_Biome,ATTRIBUTE_Plot,ATTRIBUTE_State
0,BLO1_P3_250_POS_06_05_19_1-29_01_8330.mzXML,BLO1-250,Faboideae,Amburana,Amburana cearensis,Caatinga,BLO1,Piaui
1,MACAU2_116_POS_06_02_19_1-27_01_6866.mzXML,MCS2-116,Faboideae,Amburana,Amburana cearensis,Caatinga,MCS2,Bahia
2,MACAU_136_POS_06_02_19_1-24_01_6862.mzXML,MCS2-136,Faboideae,Amburana,Amburana cearensis,Caatinga,MCS2,Bahia
3,MACAU_59_POS_06_02_19_1-20_01_6857.mzXML,MCS2-59,Faboideae,Amburana,Amburana cearensis,Caatinga,MCS2,Bahia
4,PAT2_720_26_10_18_1-18_01_5802.mzXML,PAT2-720,Faboideae,Amburana,Amburana cearensis,Caatinga,PAT02,Paraiba

In [32]:
meta.columns

Index(['filename', 'ATTRIBUTE_SampleNumber', 'ATTRIBUTE_Subfamily',
       'ATTRIBUTE_Genre', 'ATTRIBUTE_Specie', 'ATTRIBUTE_Biome',
       'ATTRIBUTE_Plot', 'ATTRIBUTE_State'],
      dtype='object')

In [33]:
meta['ATTRIBUTE_State'].value_counts()

Piaui                  60
Ceara                  54
Paraiba                26
Pernambuco             22
Bahia                  13
Rio Grande do Norte    12
Minas Gerais            8
Name: ATTRIBUTE_State, dtype: int64

In [34]:
!pyclassrich --help

Usage: pyclassrich [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  classification
  impact-plot
  ont-graph
  univariate-analysis

In [35]:
!pyclassrich impact-plot --help

Usage: pyclassrich impact-plot [OPTIONS]

Options:
  --uni TEXT     Optional univariate table file
  --param TEXT   Parameter file
  --cfield TEXT  Class prefix: class, superclass or subclass
  --nfield TEXT  Column containing compound identifier
  --method TEXT  Enrichment test method: kstest or gsea
  --sca INTEGER  Scaling factor for plot
  --top INTEGER  Top classes to display
  --out TEXT     Output directory
  --help         Show this message and exit.

In [36]:
import yaml

with open('param.yaml', 'w') as f:
    yaml.dump(params, f)

In [ ]:
# COPIE E RODE NA LINHA DE COMANDO

pyclassrich impact-plot \
    --param param.yaml \
    --cfield class \
    --nfield compound\ names \
    --method kstest \
    --sca 10 \
    --top 10 \
    --out impact_plot_95eb54