In [1]:
!gseapy --help

usage: gseapy [-h] [--version]
              {gsea,prerank,ssgsea,replot,enrichr,biomart} ...

gseapy -- Gene Set Enrichment Analysis in Python

positional arguments:
  {gsea,prerank,ssgsea,replot,enrichr,biomart}
    gsea                Main GSEApy Function: run GSEApy instead of GSEA.
    prerank             Run GSEApy Prerank tool on preranked gene list.
    ssgsea              Run Single Sample GSEA.
    replot              Reproduce GSEA desktop output figures.
    enrichr             Using Enrichr API to perform GO analysis.
    biomart             Using BioMart API to convert gene ids.

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit

For command line options of each command, type: gseapy COMMAND -h

In [2]:
!gseapy gsea --help

usage: gseapy gsea [-h] -d DATA -c CLS -g GMT [-t perType] [-o] [-f]
                   [--fs width height] [--graph int] [--no-plot] [-v]
                   [-n nperm] [--min-size int] [--max-size int] [-w float]
                   [-m] [-a] [-s] [-p procs]

optional arguments:
  -h, --help            show this help message and exit

Input files arguments:
  -d DATA, --data DATA  Input gene expression dataset file in txt format.Same
                        with GSEA.
  -c CLS, --cls CLS     Input class vector (phenotype) file in CLS format.
                        Same with GSEA.
  -g GMT, --gmt GMT     Gene set database in GMT format. Same with GSEA.
  -t perType, --permu-type perType
                        Permutation type. Same with GSEA, choose from
                        {'gene_set', 'phenotype'}

Output arguments:
  -o , --outdir         The GSEApy output directory. Default: the current
                        working directory
  -f , --format         File extensions supported by Matplotlib active
                        backend, choose from {'pdf', 'png', 'jpeg','ps',
                        'eps','svg'}. Default: 'pdf'.
  --fs width height, --figsize width height
                        The figsize keyword argument need two parameters to
                        define. Default: (6.5, 6)
  --graph int           Numbers of top graphs produced. Default: 20
  --no-plot             Speed up computing by suppressing the plot output.This
                        is useful only if data are interested. Default: False.
  -v, --verbose         Increase output verbosity, print out progress of your
                        job

GSEA advanced arguments:
  -n nperm, --permu-num nperm
                        Number of random permutations. For calculating
                        esnulls. Default: 1000
  --min-size int        Min size of input genes presented in Gene Sets.
                        Default: 15
  --max-size int        Max size of input genes presented in Gene Sets.
                        Default: 500
  -w float, --weight float
                        Weighted_score of rank_metrics. For weighting input
                        genes. Choose from {0, 1, 1.5, 2}. Default: 1
  -m , --method         Methods to calculate correlations of ranking metrics.
                        Choose from {'signal_to_noise', 'abs_signal_to_noise',
                        't_test', 'ratio_of_classes',
                        'diff_of_classes','log2_ratio_of_classes'}. Default:
                        'log2_ratio_of_classes'
  -a, --ascending       Rank metric sorting order. If the -a flag was chosen,
                        then ascending equals to True. Default: False.
  -s , --seed           Number of random seed. Default: None
  -p procs, --threads procs
                        Number of Processes you are going to use. Default: 1

In [39]:
import gseapy as gp
import pandas as pd
import numpy as np

In [4]:
phenoA, phenoB, class_vector =  gp.parser.gsea_cls_parser("P53.cls")

In [5]:
#class_vector used to indicate group attributes for each sample
print(class_vector)

['MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'MUT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT', 'WT']

In [6]:
gene_exp = pd.read_csv("P53.txt", sep="\t")
gene_exp.head()

,NAME,DESCRIPTION,786-0,BT-549,CCRF-CEM,COLO 205,EKVX,HCC-2998,HCT-15,HOP-62,...,MCF7,MOLT-4,NCI-H460,OVCAR-4,SF-539,SK-MEL-5,SR,UACC-257,UACC-62,UO-31
0,TACC2,na,46.05,82.17,16.87,98.60,141.02,114.32,134.34,44.95,...,68.14,32.21,105.89,64.99,53.52,85.47,18.69,32.16,45.70,48.13
1,C14orf132,na,108.34,59.04,25.61,33.11,42.53,9.12,9.36,310.96,...,159.32,10.71,13.59,53.78,57.57,86.80,17.30,102.66,62.16,73.44
2,AGER,na,42.20,25.75,76.01,40.41,32.17,48.28,58.27,42.40,...,51.50,61.48,44.44,45.68,54.17,62.53,83.18,56.57,50.40,36.75
3,32385_at,na,7.43,13.94,8.55,21.13,15.09,19.05,16.47,7.60,...,30.77,21.27,13.36,16.19,12.07,17.62,22.60,4.50,14.59,11.33
4,RBM17,na,11.40,3.00,3.16,2.34,4.43,1.56,6.04,6.16,...,1.62,2.77,4.42,8.91,12.28,3.04,10.13,8.32,8.23,3.91

In [7]:
len(class_vector)

50

In [8]:
gene_exp.shape

(10100, 52)

In [9]:
# run gsea
# enrichr libraries are supported by gsea module. Just provide the name

gs_res = gp.gsea(data=gene_exp, # or data='./P53_resampling_data.txt'
                 gene_sets='KEGG_2016', # enrichr library names
                 cls= 'P53.cls', # cls=class_vector
                 # set permutation_type to phenotype if samples >=15
                 permutation_type='phenotype',
                 permutation_num=100, # reduce number to speed up test
                 outdir=None,  # do not write output to disk
                 no_plot=True, # Skip plotting
                 method='signal_to_noise',
                 processes=4, seed= 7,
                 format='png')

In [10]:
#access the dataframe results throught res2d attribute
gs_res.res2d.sort_index().head()

,es,nes,pval,fdr,geneset_size,matched_size,genes,ledge_genes
Term,,,,,,,,
ABC transporters Homo sapiens hsa02010,-0.328540,-1.174290,0.252174,0.594993,44,33,ABCD3;ABCD4;ABCA2;ABCB7;ABCD1;ABCA3;ABCC9;ABCB...,ABCG1;ABCC5;ABCB4;TAP2;CFTR;ABCC10;ABCB11;ABCC...
AGE-RAGE signaling pathway in diabetic complications Homo sapiens hsa04933,-0.261859,-1.046512,0.386555,0.739592,101,90,F3;PIK3CA;PLCE1;NRAS;RELA;RAC1;PLCB3;MAPK13;MA...,COL4A1;AKT3;VCAM1;PIK3R3;SMAD3;STAT1;THBD;SELE...
AMPK signaling pathway Homo sapiens hsa04152,0.198892,0.899468,0.714286,1.000000,124,89,PPP2R5B;PIK3CA;PPP2R5C;CREB3L1;PRKAA1;CREB3;PP...,PPP2R5B;PIK3CA;PPP2R5C;CREB3L1;PRKAA1;CREB3;PP...
Acute myeloid leukemia Homo sapiens hsa05221,0.196716,0.710123,0.900000,1.000000,57,50,MAP2K1;PIK3CA;NRAS;RELA;RPS6KB2;TCF7L2;JUP;RAF...,MAP2K1;PIK3CA;NRAS;RELA;RPS6KB2;TCF7L2;JUP;RAF...
Adherens junction Homo sapiens hsa04520,0.246805,0.984227,0.477941,1.000000,74,66,EP300;YES1;CTNND1;RAC1;WASF1;ERBB2;ACTN1;PTPRF...,EP300;YES1;CTNND1;RAC1;WASF1;ERBB2;ACTN1;PTPRF...

In [12]:
help(gseaplot)

Help on function gseaplot in module gseapy.plot:

gseaplot(rank_metric, term, hit_indices, nes, pval, fdr, RES, pheno_pos='', pheno_neg='', figsize=(6, 5.5), cmap='seismic', ofname=None, **kwargs)
    This is the main function for reproducing the gsea plot.

    :param rank_metric: pd.Series for rankings, rank_metric.values.
    :param term: gene_set name
    :param hit_indices: hits indices of rank_metric.index presented in gene set S.
    :param nes: Normalized enrichment scores.
    :param pval: nominal p-value.
    :param fdr: false discovery rate.
    :param RES: running enrichment scores.
    :param pheno_pos: phenotype label, positive correlated.
    :param pheno_neg: phenotype label, negative correlated.
    :param figsize: matplotlib figsize.
    :param ofname: output file name. If None, don't save figure

In [15]:
from gseapy.plot import gseaplot
terms = gs_res.res2d.index
# Make sure that ``ofname`` is not None, if you want to save your figure to disk
gseaplot(gs_res.ranking, term=terms[0], **gs_res.results[terms[0]], ofname='tutorial_analysis.png')

In [34]:
from __future__ import  absolute_import, division
from gseapy.parser import gsea_edb_parser, gsea_gmt_parser, gsea_cls_parser
from gseapy.algorithm import enrichment_score, gsea_compute, ranking_metric
import logging

In [40]:
def preprocess(df):
    """pre-processed the data frame.new filtering methods will be implement here.
    """    
    
    df.drop_duplicates(subset=df.columns[0], inplace=True) #drop duplicate gene_names.    
    df.set_index(keys=df.columns[0], inplace=True)
    df.dropna(how='all', inplace=True)                     #drop rows with all NAs
    df2 = df.select_dtypes(include=['float64'])  + 0.001 #select numbers in DataFrame      
    
    return df2


def ranking_metric(df, method, phenoPos, phenoNeg, classes, ascending):
    """The main function to rank an expression table.
    
   :param df:      gene_expression DataFrame.    
   :param method:  The method used to calculate a correlation or ranking. Default: 'log2_ratio_of_classes'.
                   Others methods are:
   
                   1. 'signal_to_noise' 
      
                      You must have at least three samples for each phenotype to use this metric.
                      The larger the signal-to-noise ratio, the larger the differences of the means (scaled by the standard deviations);
                      that is, the more distinct the gene expression is in each phenotype and the more the gene acts as a “class marker.” 
    
                   2. 't_test'
      
                      Uses the difference of means scaled by the standard deviation and number of samples. 
                      Note: You must have at least three samples for each phenotype to use this metric.
                      The larger the tTest ratio, the more distinct the gene expression is in each phenotype 
                      and the more the gene acts as a “class marker.”
    
                   3. 'ratio_of_classes' (also referred to as fold change).
      
                      Uses the ratio of class means to calculate fold change for natural scale data.
    
                   4. 'diff_of_classes' 
      
                      Uses the difference of class means to calculate fold change for log scale data
    
                   5. 'log2_ratio_of_classes' 
      
                      Uses the log2 ratio of class means to calculate fold change for natural scale data.
                      This is the recommended statistic for calculating fold change for natural scale data.
   
      
   :param phenoPos: one of lables of phenotype's names.
   :param phenoNeg: one of lable of phenotype's names.   
   :param classes:  a list of phenotype labels, to specify which column of dataframe belongs to what catogry of phenotype.
   :param ascending:  bool or list of bool. Sort ascending vs. descending.
   :return: returns correlation to class of each variable. same format with .rnk file. gene_name in first coloum,
            correlation in second column.  
            
    visit here for more docs: http://software.broadinstitute.org/gsea/doc/GSEAUserGuideFrame.html
    """ 
        
    A = phenoPos
    B = phenoNeg
    df2 = df.T   
    df2['class'] = classes
    df_mean= df2.groupby('class').mean().T
    df_std = df2.groupby('class').std().T  
    #exclude any zero stds.
    df_mean = df_mean[df_std.sum(axis=1) !=0]
    df_std = df_std[df_std.sum(axis=1) !=0]
    
    if method == 'signal_to_noise':
        sr = (df_mean[A] - df_mean[B])/(df_std[A] + df_std[B])
    elif method == 't_test':
        sr = (df_mean[A] - df_mean[B])/ np.sqrt(df_std[A]**2/len(df_std)+df_std[B]**2/len(df_std) )
    elif method == 'ratio_of_classes':
        sr = df_mean[A] / df_mean[B]
    elif method == 'diff_of_classes':
        sr  = df_mean[A] - df_mean[B]
    elif method == 'log2_ratio_of_classes':
        sr  =  np.log2(df_mean[A] / df_mean[B])
    else:
        logging.error("Please provide correct method name!!!")        
        sys.exit()
    sr.sort_values(ascending=ascending, inplace=True)
    df3 = sr.to_frame().reset_index()
    df3.columns = ['gene_name','rank']
    df3['rank2'] = df3['rank']

    return df3

def gsea_compute(data, gmt, n, weighted_score_type, permutation_type, method,
                 phenoPos, phenoNeg, classes, ascending, seed, prerank=False):
    """compute enrichment scores and enrichment nulls. 
    
    :param data: prepreocessed expression dataframe or a pre-ranked file if prerank=True.
    :param gmt: all gene sets in .gmt file. need to call gsea_gmt_parser() to get results. 
    :param n: permutation number. default: 1000.
    :param method: ranking_metric method. see above.
    :param phenoPos: one of lables of phenotype's names. 
    :param phenoNeg: one of lable of phenotype's names.     
    :param classes: a list of phenotype labels, to specify which column of dataframe belongs to what catogry of phenotype.
    :param weighted_score_type: default:1
    :param ascending: sorting order of rankings. Default: False.
    :param seed: random seed. Default: np.random.RandomState()
    :param prerank: if true, this function will compute using pre-ranked file passed by parameter data.
    :return: 
      zipped results of es, nes, pval, fdr. Used for generating reportes and plotting.
    
      a nested list of hit indexs of input gene_list. Used for plotting.
    
      a nested list of ranked enrichment score of each input gene_sets. Used for plotting.
    
    """
    enrichment_scores = []
    w = weighted_score_type
    subsets = sorted(gmt.keys())    
    dat = data.copy()
    if prerank:
        r2 =data.copy()
    else:
        r2 = ranking_metric(df=dat, method=method, phenoPos=phenoPos, phenoNeg=phenoNeg, classes=classes, ascending=ascending)
    ranking=r2['rank'].values
    gene_list=r2['gene_name']
       
    logging.debug("Start to compute enrichment socres......................")

    rank_ES = []
    hit_ind = []    
    for subset in subsets:
        es,ind,RES = enrichment_score(gene_list=gene_list, gene_set=gmt.get(subset), 
                              weighted_score_type=w, correl_vector=ranking)
        enrichment_scores.append(es)
        rank_ES.append(RES)
        hit_ind.append(ind)
           
    logging.debug("Start to compute esnulls...............................")

    enrichment_nulls = [ [] for a in range(len(subsets)) ]
    rs = np.random.RandomState(seed)
    
    
    if permutation_type == "phenotype":
        
        dat2 = dat.T 
        for i in range(n):
            dat2.apply(rs.shuffle, axis=0) #permutation classes
            r2 = ranking_metric(df=dat2.T, method=method, phenoPos=phenoPos, phenoNeg=phenoNeg, classes=classes, ascending=ascending )
            ranking2=r2['rank']
            gene_list2=r2['gene_name'].values
        
    
        #for i in range(n):    
        #gene_list.apply(np.random.shuffle,axis=0) #permutation genes
        #r2 = ranking_metric(df=dat,method = method, classes=classes,ascending= ascending)
        #gene_list2 = shuffle_list(gene_list, rs)
        #ranking2=ranking           
            for si,subset in enumerate(subsets):
                esn = enrichment_score(gene_list=gene_list2, gene_set=gmt.get(subset), 
                                       weighted_score_type=w, correl_vector=ranking2)[0] 
                enrichment_nulls[si].append(esn)
    else:                       
        for si,subset in enumerate(subsets):
            esn = enrichment_score(gene_list=gene_list, gene_set=gmt.get(subset), weighted_score_type=w, 
                                   correl_vector=ranking, esnull=n, rs=rs)[0]                                         
            enrichment_nulls[si] = esn # esn is a list, don't need to use append method. 

    return gsea_significance(enrichment_scores, enrichment_nulls),hit_ind,rank_ES, subsets

def enrichment_score(gene_list, gene_set, weighted_score_type=1, correl_vector=None, esnull=None, rs=np.random.RandomState()):
    """This is the most important function of GSEAPY. It has the same algorithm with GSEA.
    
    :param gene_list:       The ordered gene list gene_name_list, rank_metric['gene_name']
    :param gene_set:        gene_sets in gmt file, please used gsea_gmt_parser to get gene_set.                            
    :param weighted_score_type:  It's indentical to gsea's weighted_score method. weighting by the correlation 
                            is a very reasonable choice that allows significant gene sets with less than perfect coherence. 
                            options: 0(classic),1,1.5,2. default:1. if one is interested in penalizing sets for lack of 
                            coherence or to discover sets with any type of nonrandom distribution of tags, a value p < 1 
                            might be appropriate. On the other hand, if one uses sets with largenumber of genes and only 
                            a small subset of those is expected to be coherent, then one could consider using p > 1. 
                            Our recommendation is to use p = 1 and use other settings only if you are very experienced 
                            with the method and its behavior.
                             
    :param correl_vector:   A vector with the correlations (e.g. signal to noise scores) corresponding to the genes in 
                            the gene list. Or rankings, rank_metric['rank'].values
    :param esnull:          Only used this paramter when computing esnuall for statistial testing. set the esnull value
                            equal to the permutation number.
    :param rs:              Random state for initialize gene list shuffling. Default: np.random.RandomState(seed=None)
       
    :return:
    
     ES: Enrichment score (real number between -1 and +1) 
     
     hit_index: index of a gene in gene_list, if gene included in gene_set.
     
     RES: Numerical vector containing the running enrichment score for all locations in the gene list .
             
    """
 
    axis = 0
    N = len(gene_list)  
  
    #Test whether each element of a 1-D array is also present in a second array
    #It's more intuitived here than orginal enrichment_score source code.
    #use .astype to covert bool to intergers  
    tag_indicator = np.in1d(gene_list, gene_set, assume_unique=True).astype(int)  # notice that the sign is 0 (no tag) or 1 (tag)

    if (weighted_score_type == 0 ): 
        correl_vector = np.repeat(1, N)
    else:
        correl_vector = np.abs(correl_vector**weighted_score_type)
        
          
    #get indices of tag_indicator    
    hit_ind = np.flatnonzero(tag_indicator).tolist() 

    Nhint = np.sum(tag_indicator) 
    sum_correl_tag = np.sum(correl_vector[tag_indicator.astype(bool)])
    
    # if used for compute esnull, set esnull equal to permutation number, e.g. 1000    
    if esnull:
        tag_indicator = tag_indicator.repeat(esnull).reshape(N, esnull).T
        correl_vector = correl_vector.repeat(esnull).reshape(N, esnull).T

        # gene list permutation
        for i in range(esnull):
            rs.shuffle(tag_indicator[i])

        # set axis to 1, because we have 2 dimentional array
        axis = 1
        Nhint = np.sum(tag_indicator, axis=axis).reshape(esnull, 1)
        sum_correl_tag = np.sum(correl_vector*tag_indicator, axis=axis).reshape(esnull, 1)
    ''' 
    #similar results could be obtained when computing esnull using code below
    # 
    if esnull:
        tag_null = np.empty((esnull, N))
        i=0
        while i < esnull:
            rs.shuffle(tag_indicator)
            tag_null[i] = tag_indicator
            i +=1
        axis = 1
        tag_indicator = tag_null
    '''


    #compute ES score, the code below is identical to gsea enrichment_score method.    
    no_tag_indicator = 1 - tag_indicator
    Nmiss =  N - Nhint 
    norm_tag =  1.0/sum_correl_tag
    norm_no_tag = 1.0/Nmiss
       
    RES = np.cumsum(tag_indicator * correl_vector * norm_tag - no_tag_indicator * norm_no_tag, axis=axis)      
    max_ES = np.max(RES, axis=axis)
    min_ES = np.min(RES, axis=axis)
    
    es = np.where(np.abs(max_ES) > np.abs(min_ES), max_ES, min_ES)
   
    return es.tolist(), hit_ind, RES.tolist()

In [44]:
min_size=15 
max_size=500
permutation_n=1000 
weighted_score_type=1
permutation_type='phenotype'
method='ratio_of_classes'
ascending=False

df = gene_exp.copy()
dat = preprocess(df)

phenoPos, phenoNeg, classes =  gsea_cls_parser("P53.cls")

dat2 = ranking_metric(df=dat, method=method, phenoPos=phenoPos, 
                      phenoNeg=phenoNeg, classes=classes, ascending=ascending)

In [45]:
dat2.head()

  gene_name       rank      rank2
0      HBG2  32.791629  32.791629
1       PIP  23.529585  23.529585
2     FABP4  13.008015  13.008015
3  325_s_at  12.198642  12.198642
4     SULF1  12.182041  12.182041

In [46]:
gmt = gsea_gmt_parser('KEGG_2016', min_size=min_size, max_size=max_size,gene_list=dat2['gene_name'].values)
gmt

{'SNARE interactions in vesicular transport Homo sapiens hsa04130': ['STX8',
  'BET1L',
  'VAMP7',
  'VAMP8',
  'VAMP1',
  'VAMP2',
  'VAMP5',
  'SEC22B',
  'VAMP3',
  'STX1B',
  'VAMP4',
  'STX1A',
  'BET1',
  'STX16',
  'STX18',
  'GOSR1',
  'STX17',
  'SNAP23',
  'GOSR2',
  'STX19',
  'STX10',
  'USE1',
  'STX11',
  'STX7',
  'VTI1B',
  'STX6',
  'VTI1A',
  'YKT6',
  'STX5',
  'BNIP1',
  'STX4',
  'SNAP29',
  'STX3',
  'STX2'],
 'Protein processing in endoplasmic reticulum Homo sapiens hsa04141': ['SEC24A',
  'SEC24C',
  'SEC24B',
  'HSPA1L',
  'FBXO2',
  'MOGS',
  'AMFR',
  'YOD1',
  'RBX1',
  'ERN1',
  'NSFL1C',
  'MAPK10',
  'DNAJB11',
  'DNAJB12',
  'HSPA1A',
  'BAX',
  'RNF185',
  'ERP29',
  'PREB',
  'SEC24D',
  'PLAA',
  'HSPA1B',
  'PARK2',
  'ATF6B',
  'UBE2D3',
  'TUSC3',
  'PPP1R15A',
  'UBE2D4',
  'UBE2D1',
  'UBE2D2',
  'LOC102724652',
  'RRBP1',
  'RNF5',
  'HSP90B1',
  'CAPN1',
  'CAPN2',
  'MAP3K5',
  'PDIA4',
  'PDIA3',
  'XBP1',
  'WFS1',
  'LMAN1L',
  'EDEM1',
  'EDEM2',
  'EDEM3',
  'TRAF2',
  'PDIA6',
  'EIF2S1',
  'CKAP4',
  'NPLOC4',
  'DDOST',
  'DNAJC10',
  'STT3B',
  'STT3A',
  'HYOU1',
  'ATF6',
  'CRYAB',
  'ATF4',
  'CRYAA',
  'HSPA4L',
  'ERO1LB',
  'VCP',
  'NGLY1',
  'CUL1',
  'SEL1L2',
  'UBE2J1',
  'HSPBP1',
  'UBE2J2',
  'HSPH1',
  'ATXN3L',
  'BAG1',
  'BAG2',
  'TXNDC5',
  'SEC31A',
  'SEC63',
  'SIL1',
  'SEC62',
  'SKP1',
  'MAP2K7',
  'SEC31B',
  'SEC13',
  'HSP90AA1',
  'HSPA6',
  'HSPA5',
  'SSR3',
  'HSPA8',
  'EIF2AK2',
  'EIF2AK1',
  'SSR4',
  'EIF2AK4',
  'HSPA2',
  'EIF2AK3',
  'RAD23B',
  'UBE2G2',
  'RAD23A',
  'MARCH6',
  'UBE2G1',
  'DNAJC3',
  'DNAJC1',
  'UBQLNL',
  'DNAJC5',
  'BCL2',
  'CALR',
  'VIMP',
  'NFE2L2',
  'TRAM1',
  'SAR1A',
  'UFD1L',
  'SAR1B',
  'RPN1',
  'SEL1L',
  'RPN2',
  'DNAJB2',
  'DNAJB1',
  'ATXN3',
  'CASP12',
  'ERLEC1',
  'SEC61G',
  'SEC61B',
  'SSR1',
  'SSR2',
  'DNAJC5G',
  'MAN1A2',
  'MAN1A1',
  'UBXN6',
  'MBTPS1',
  'MBTPS2',
  'BCAP31',
  'DNAJC5B',
  'UBE2E2',
  'UBE2E3',
  'UBE4B',
  'SYVN1',
  'UBE2E1',
  'SVIP',
  'DNAJA2',
  'DNAJA1',
  'DAD1',
  'MAN1B1',
  'CANX',
  'P4HB',
  'DDIT3',
  'STUB1',
  'SEC23B',
  'SEC23A',
  'PRKCSH',
  'HSP90AB1',
  'DERL2',
  'DERL3',
  'DERL1',
  'HERPUD1',
  'ERO1L',
  'LMAN1',
  'SEC61A2',
  'LMAN2',
  'MAPK9',
  'MAPK8',
  'GANAB',
  'OS9',
  'SEC61A1',
  'UBQLN2',
  'MAN1C1',
  'UBQLN1',
  'BAK1',
  'FBXO6',
  'UGGT2',
  'UGGT1',
  'UBQLN4',
  'UBQLN3'],
 'N-Glycan biosynthesis Homo sapiens hsa00510': ['DOLPP1',
  'ALG14',
  'MOGS',
  'ALG13',
  'ALG12',
  'ALG11',
  'ALG10',
  'DPM1',
  'DPM2',
  'DPM3',
  'ALG10B',
  'B4GALT3',
  'DPAGT1',
  'B4GALT1',
  'B4GALT2',
  'RPN1',
  'TUSC3',
  'RPN2',
  'FUT8',
  'MGAT5B',
  'MAN1A2',
  'MAN1A1',
  'ALG9',
  'ST6GAL2',
  'ALG8',
  'ST6GAL1',
  'ALG5',
  'ALG6',
  'ALG3',
  'DOLK',
  'ALG1',
  'ALG2',
  'MGAT4D',
  'DDOST',
  'MGAT4A',
  'MGAT4B',
  'DAD1',
  'MGAT4C',
  'MAN1B1',
  'STT3B',
  'STT3A',
  'GANAB',
  'MAN2A2',
  'MGAT5',
  'MAN1C1',
  'MGAT2',
  'MAN2A1',
  'MGAT3',
  'MGAT1'],
 'Glycosphingolipid biosynthesis - lacto and neolacto series Homo sapiens hsa00601': ['ST8SIA1',
  'B3GALT5',
  'B3GNT5',
  'B3GNT4',
  'B3GNT3',
  'B3GNT2',
  'B3GNT1',
  'B4GALT3',
  'B4GALT4',
  'B4GALT1',
  'B4GALT2',
  'GCNT2',
  'FUT1',
  'FUT3',
  'ABO',
  'FUT2',
  'FUT5',
  'FUT4',
  'FUT7',
  'FUT6',
  'FUT9',
  'B3GALT1',
  'B3GALT2',
  'ST3GAL6',
  'ST3GAL3',
  'ST3GAL4'],
 'Sphingolipid metabolism Homo sapiens hsa00600': ['ARSA',
  'CERS4',
  'CERS5',
  'CERS6',
  'SPHK2',
  'SPHK1',
  'SGPP2',
  'SGPP1',
  'ACER3',
  'ACER2',
  'GALC',
  'GLB1',
  'ACER1',
  'PPAP2A',
  'PPAP2C',
  'PPAP2B',
  'GLA',
  'DEGS2',
  'DEGS1',
  'CERS1',
  'CERS2',
  'B4GALT6',
  'CERS3',
  'GAL3ST1',
  'ASAH2',
  'GBA',
  'SGMS2',
  'CERK',
  'SGMS1',
  'GBA2',
  'ASAH1',
  'NEU3',
  'SMPD4',
  'NEU4',
  'SMPD3',
  'SPTLC1',
  'UGCG',
  'UGT8',
  'SGPL1',
  'SPTLC2',
  'KDSR',
  'SPTLC3',
  'SMPD2',
  'NEU1',
  'NEU2',
  'SMPD1',
  'ENPP7'],
 'Lysosome Homo sapiens hsa04142': ['CD164',
  'ENTPD4',
  'AP1S1',
  'AP1B1',
  'CTNS',
  'GALNS',
  'GLA',
  'CD68',
  'ATP6V0D1',
  'IDUA',
  'ASAH1',
  'GGA1',
  'GGA3',
  'GGA2',
  'AP3M2',
  'LAPTM4B',
  'GNPTAB',
  'LAPTM4A',
  'LAMP2',
  'LAMP1',
  'LAMP3',
  'AP3M1',
  'ABCA2',
  'ARSA',
  'ARSB',
  'IGF2R',
  'PSAPL1',
  'ATP6V0C',
  'MANBA',
  'ATP6V0B',
  'NAPSA',
  'DNASE2B',
  'SLC11A1',
  'ATP6AP1',
  'SLC11A2',
  'M6PR',
  'AP4B1',
  'LGMN',
  'PPT2',
  'PPT1',
  'TPP1',
  'GNS',
  'NAGPA',
  'LIPA',
  'AP1S3',
  'ATP6V0A4',
  'AP1S2',
  'ARSG',
  'ATP6V1H',
  'ATP6V0A1',
  'ATP6V0A2',
  'CTSB',
  'HGSNAT',
  'CTSA',
  'FUCA1',
  'AP3B2',
  'NPC1',
  'AP3B1',
  'SUMF1',
  'NPC2',
  'GNPTG',
  'MAN2B1',
  'DNASE2',
  'CTSZ',
  'CLTC',
  'CLTB',
  'CLTA',
  'ABCB9',
  'LITAF',
  'CTSW',
  'CTSV',
  'CTSS',
  'MFSD8',
  'CTSO',
  'PSAP',
  'IDS',
  'CTSL',
  'NEU1',
  'CLTCL1',
  'CTSK',
  'ACP5',
  'CTSH',
  'AP4S1',
  'CTSG',
  'AP1M1',
  'CTSF',
  'CTSE',
  'ACP2',
  'CTSD',
  'AP1M2',
  'CTSC',
  'SORT1',
  'GAA',
  'NAGA',
  'LAPTM5',
  'AP3D1',
  'MCOLN1',
  'GALC',
  'GLB1',
  'PLA2G15',
  'ATP6V0D2',
  'SCARB2',
  'CD63',
  'GBA',
  'HEXA',
  'HEXB',
  'TCIRG1',
  'AP4E1',
  'SGSH',
  'CLN5',
  'AP4M1',
  'CLN3',
  'AP1G1',
  'HYAL1',
  'NAGLU',
  'GM2A',
  'AP1G2',
  'SMPD1',
  'AP3S1',
  'AGA',
  'AP3S2',
  'GUSB',
  'SLC17A5'],
 'Synaptic vesicle cycle Homo sapiens hsa04721': ['UNC13C',
  'UNC13A',
  'UNC13B',
  'ATP6V1E1',
  'DNM1',
  'DNM2',
  'DNM3',
  'STX1B',
  'STX1A',
  'SNAP25',
  'STXBP1',
  'ATP6V0D1',
  'NAPA',
  'CLTC',
  'CLTB',
  'CLTA',
  'CLTCL1',
  'AP2S1',
  'SLC18A1',
  'ATP6V1E2',
  'STX3',
  'STX2',
  'SLC18A2',
  'SLC18A3',
  'ATP6V1G1',
  'NSF',
  'ATP6V0C',
  'ATP6V1G2',
  'ATP6V0E1',
  'ATP6V1G3',
  'ATP6V0B',
  'ATP6V0E2',
  'SLC32A1',
  'SYT1',
  'AP2B1',
  'VAMP2',
  'ATP6V0D2',
  'ATP6V1B1',
  'ATP6V1B2',
  'ATP6V1A',
  'CPLX1',
  'RAB3A',
  'ATP6V1D',
  'CACNA1A',
  'TCIRG1',
  'CACNA1B',
  'AP2A2',
  'AP2A1',
  'CPLX3',
  'CPLX2',
  'CPLX4',
  'RIMS1',
  'SLC17A6',
  'SLC17A7',
  'ATP6V0A4',
  'SLC17A8',
  'ATP6V1F',
  'ATP6V1C1',
  'ATP6V1H',
  'ATP6V0A1',
  'ATP6V1C2',
  'ATP6V0A2',
  'AP2M1'],
 'Collecting duct acid secretion Homo sapiens hsa04966': ['ATP6V1G1',
  'ATP6V0C',
  'ATP6V1G2',
  'ATP6V0E1',
  'ATP6V1G3',
  'ATP6V0E2',
  'ATP6V1E1',
  'ATP4B',
  'ATP4A',
  'ATP6V0D2',
  'ATP6V1B1',
  'ATP6V1B2',
  'ATP6V1A',
  'ATP6V1D',
  'ATP6V0D1',
  'TCIRG1',
  'CLCNKB',
  'SLC4A1',
  'CA2',
  'ATP6V0A4',
  'SLC12A7',
  'ATP6V1F',
  'ATP6V1E2',
  'ATP6V1C1',
  'ATP6V0A1',
  'ATP6V1C2',
  'ATP6V0A2'],
 'Vibrio cholerae infection Homo sapiens hsa05110': ['ATP6V1E1',
  'SLC12A2',
  'ATP6V0D1',
  'KDELR1',
  'ARF1',
  'KDELR2',
  'ADCY3',
  'ADCY9',
  'ACTB',
  'MUC2',
  'SEC61G',
  'SEC61B',
  'ATP6V1E2',
  'PDIA4',
  'ATP6V1G1',
  'ATP6V0C',
  'ATP6V1G2',
  'ATP6V0E1',
  'ATP6V1G3',
  'ATP6V0B',
  'ATP6V0E2',
  'ATP6AP1',
  'PRKCA',
  'TJP2',
  'TJP1',
  'KCNQ1',
  'GNAS',
  'KDELR3',
  'ATP6V0D2',
  'ATP6V1B1',
  'ATP6V1B2',
  'CFTR',
  'ATP6V1A',
  'ATP6V1D',
  'ACTG1',
  'TCIRG1',
  'ERO1L',
  'SEC61A2',
  'PRKACG',
  'SEC61A1',
  'ATP6V0A4',
  'PLCG1',
  'PLCG2',
  'PRKACB',
  'ATP6V1F',
  'ATP6V1C1',
  'ATP6V1H',
  'ATP6V0A1',
  'ATP6V1C2',
  'PRKACA',
  'ATP6V0A2'],
 'Epithelial cell signaling in Helicobacter pylori infection Homo sapiens hsa05120': ['LYN',
  'JUN',
  'ATP6V1E1',
  'PTPN11',
  'MAPK13',
  'MAPK14',
  'MAPK11',
  'NFKBIA',
  'MAPK12',
  'MAPK10',
  'CXCL8',
  'RELA',
  'ATP6V0D1',
  'IGSF5',
  'NOD1',
  'CXCL1',
  'EGFR',
  'PAK1',
  'CASP3',
  'JAM2',
  'ATP6V1E2',
  'JAM3',
  'MAP2K4',
  'ATP6V1G1',
  'ATP6V0C',
  'ATP6V1G2',
  'ATP6V0E1',
  'ATP6V1G3',
  'ATP6V0B',
  'ATP6V0E2',
  'ATP6AP1',
  'CHUK',
  'ADAM10',
  'NFKB1',
  'CDC42',
  'TJP1',
  'ADAM17',
  'MET',
  'ATP6V0D2',
  'MAP3K14',
  'HBEGF',
  'ATP6V1B1',
  'ATP6V1B2',
  'ATP6V1A',
  'SRC',
  'ATP6V1D',
  'TCIRG1',
  'F11R',
  'IKBKB',
  'MAPK9',
  'MAPK8',
  'CXCR2',
  'CXCR1',
  'PTPRZ1',
  'CCL5',
  'ATP6V0A4',
  'PLCG1',
  'RAC1',
  'PLCG2',
  'CSK',
  'ATP6V1F',
  'IKBKG',
  'ATP6V1C1',
  'ATP6V1H',
  'ATP6V0A1',
  'ATP6V1C2',
  'ATP6V0A2',
  'GIT1'],
 'Rheumatoid arthritis Homo sapiens hsa05323': ['TGFB1',
  'IL11',
  'TGFB3',
  'TGFB2',
  'JUN',
  'ATP6V1E1',
  'IL15',
  'MMP1',
  'ANGPT1',
  'CCL20',
  'MMP3',
  'IL18',
  'VEGFA',
  'IL1A',
  'TLR2',
  'IL1B',
  'CXCL12',
  'IL6',
  'IL23A',
  'IFNG',
  'TEK',
  'HLA-DRA',
  'HLA-DQB1',
  'CD28',
  'TLR4',
  'CXCL8',
  'CD86',
  'ATP6V0D1',
  'CCL3L1',
  'TNFRSF11A',
  'CSF2',
  'CSF1',
  'CCL3L3',
  'CD80',
  'TNF',
  'CXCL1',
  'CXCL6',
  'CXCL5',
  'LOC102723407',
  'CTSL',
  'CTSK',
  'ACP5',
  'CTLA4',
  'ATP6V1E2',
  'HLA-DOB',
  'HLA-DQA2',
  'HLA-DOA',
  'HLA-DQA1',
  'ATP6V1G1',
  'ATP6V0C',
  'ATP6V1G2',
  'ATP6V0E1',
  'ATP6V1G3',
  'ATP6V0B',
  'ATP6V0E2',
  'HLA-DRB5',
  'ATP6AP1',
  'TNFSF13',
  'FOS',
  'IL17A',
  'LTB',
  'HLA-DPB1',
  'ATP6V0D2',
  'HLA-DRB4',
  'HLA-DRB3',
  'ATP6V1B1',
  'ATP6V1B2',
  'HLA-DRB1',
  'ITGB2',
  'ATP6V1A',
  'FLT1',
  'ATP6V1D',
  'TCIRG1',
  'ITGAL',
  'TNFSF13B',
  'ICAM1',
  'HLA-DMB',
  'CCL5',
  'TNFSF11',
  'HLA-DPA1',
  'ATP6V0A4',
  'CCL3',
  'CCL2',
  'ATP6V1F',
  'ATP6V1C1',
  'HLA-DMA',
  'ATP6V1H',
  'ATP6V0A1',
  'ATP6V1C2',
  'ATP6V0A2'],
 'Phagosome Homo sapiens hsa04145': ['DYNC2H1',
  'ATP6V1E1',
  'TAP2',
  'TAP1',
  'TUBA4A',
  'TUBA8',
  'DYNC1LI1',
  'DYNC1LI2',
  'MARCO',
  'CD209',
  'NCF1',
  'CLEC4M',
  'ATP6V0D1',
  'STX18',
  'TUBAL3',
  'TUBB1',
  'MPO',
  'TUBA3C',
  'STX12',
  'ACTB',
  'COMP',
  'TUBB8',
  'TUBA3E',
  'TUBB6',
  'TUBA3D',
  'LAMP2',
  'LAMP1',
  'TUBB3',
  'STX7',
  'RILP',
  'ATP6V1E2',
  'HLA-DOB',
  'HLA-DOA',
  'MSR1',
  'ATP6V0C',
  'ATP6V0B',
  'HLA-DRB5',
  'ATP6AP1',
  'HLA-C',
  'M6PR',
  'CYBB',
  'HLA-A',
  'CYBA',
  'HLA-B',
  'HLA-G',
  'HLA-E',
  'HLA-F',
  'HGS',
  'RAB5A',
  'HLA-DRB4',
  'NOX1',
  'RAB5B',
  'HLA-DRB3',
  'VAMP3',
  'ATP6V1B1',
  'ATP6V1B2',
  'NOX3',
  'HLA-DRB1',
  'ATP6V1A',
  'ATP6V1D',
  'NCF2',
  'TFRC',
  'NCF4',
  'ACTG1',
  'CORO1A',
  'C3',
  'ATP6V0A4',
  'CD14',
  'ATP6V1F',
  'ATP6V1C1',
  'ATP6V1H',
  'ATP6V0A1',
  'ATP6V1C2',
  'ATP6V0A2',
  'ITGA5',
  'SFTPD',
  'TUBB',
  'ITGA2',
  'TUBB2A',
  'TLR2',
  'FCGR2A',
  'FCGR2B',
  'TUBB2B',
  'PIKFYVE',
  'HLA-DRA',
  'HLA-DQB1',
  'PIK3C3',
  'TLR6',
  'CALR',
  'FCGR2C',
  'TLR4',
  'RAB7A',
  'RAB7B',
  'RAB5C',
  'CTSS',
  'LOC102723407',
  'FCGR3A',
  'FCGR3B',
  'CLEC7A',
  'CTSL',
  'SEC61G',
  'SEC61B',
  'CD36',
  'DYNC1I2',
  'HLA-DQA2',
  'DYNC1I1',
  'HLA-DQA1',
  'ATP6V1G1',
  'ATP6V1G2',
  'ATP6V0E1',
  'ATP6V1G3',
  'ATP6V0E2',
  'TUBB4B',
  'TUBB4A',
  'CANX',
  'HLA-DPB1',
  'SFTPA1',
  'PLA2R1',
  'SFTPA2',
  'ATP6V0D2',
  'SEC22B',
  'DYNC1H1',
  'ITGB2',
  'ITGB1',
  'COLEC12',
  'COLEC11',
  'C1R',
  'ITGB5',
  'ITGB3',
  'TCIRG1',
  'THBS1',
  'THBS3',
  'ITGAM',
  'TUBA1A',
  'THBS2',
  'FCAR',
  'EEA1',
  'THBS4',
  'SEC61A2',
  'TUBA1C',
  'HLA-DMB',
  'TUBA1B',
  'FCGR1A',
  'MRC1',
  'SEC61A1',
  'MRC2',
  'HLA-DPA1',
  'NOS1',
  'RAC1',
  'ITGAV',
  'HLA-DMA',
  'SCARB1',
  'OLR1',
  'MBL2'],
 'Tuberculosis Homo sapiens hsa05152': ['TGFB1',
  'TGFB3',
  'CD74',
  'TGFB2',
  'BAD',
  'MAPK13',
  'MAPK14',
  'MAPK11',
  'MAPK12',
  'MAPK10',
  'CLEC4E',
  'IL23A',
  'RFX5',
  'CD209',
  'BAX',
  'CLEC4M',
  'CALM2',
  'CALM3',
  'RAF1',
  'CALM1',
  'RELA',
  'ATP6V0D1',
  'CALML6',
  'CALML3',
  'NOD2',
  'TNF',
  'CALML5',
  'LAMP2',
  'LAMP1',
  'AKT3',
  'AKT1',
  'AKT2',
  'HLA-DOB',
  'HLA-DOA',
  'ARHGEF12',
  'CREBBP',
  'IFNA13',
  'IFNA14',
  'ATP6V0C',
  'ATP6V0B',
  'HLA-DRB5',
  'IFNA16',
  'ATP6AP1',
  'IFNA17',
  'PLK3',
  'RFXANK',
  'TIRAP',
  'NFKB1',
  'MYD88',
  'CREB1',
  'RFXAP',
  'TRAF6',
  'RAB5A',
  'HLA-DRB4',
  'RAB5B',
  'HLA-DRB3',
  'IFNA10',
  'HLA-DRB1',
  'BCL10',
  'CORO1A',
  'C3',
  'PPP3R1',
  'PPP3R2',
  'CYP27B1',
  'ATP6V0A4',
  'IL12B',
  'IL12A',
  'CD14',
  'ATP6V1H',
  'ATP6V0A1',
  'IFNA21',
  'ATP6V0A2',
  'RHOA',
  'HSPA9',
  'VDR',
  'IL10',
  'APAF1',
  'KSR1',
  'CARD9',
  'SPHK2',
  'IL10RB',
  'IL10RA',
  'SPHK1',
  'IRAK4',
  'IL18',
  'TNFRSF1A',
  'IL1A',
  'TLR2',
  'IL1B',
  'TLR1',
  'FCGR2A',
  'FCGR2B',
  'IL6',
  'IFNG',
  'HLA-DRA',
  'HLA-DQB1',
  'TLR9',
  'BCL2',
  'CYCS',
  'PIK3C3',
  'TLR6',
  'FCGR2C',
  'TLR4',
  'RAB7A',
  'RAB5C',
  'TRADD',
  'CTSS',
  'PPP3CA',
  'LOC102723407',
  'PPP3CB',
  'FCGR3A',
  'CASP8',
  'PPP3CC',
  'FCGR3B',
  'CASP9',
  'IRAK2',
  'CLEC7A',
  'CASP10',
  'IRAK1',
  'LBP',
  'CASP3',
  'FADD',
  'RIPK2',
  'FCER1G',
  'CIITA',
  'CTSD',
  'HLA-DQA2',
  'CAMP',
  'HLA-DQA1',
  'CR1',
  'STAT1',
  'IFNGR1',
  'NFYB',
  'SYK',
  'NFYC',
  'IFNGR2',
  'HLA-DPB1',
  'PLA2R1',
  'ATP6V0D2',
  'IFNA6',
  'ITGB2',
  'CEBPB',
  'CAMK2D',
  'IFNA5',
  'SRC',
  'IFNA8',
  'IFNA7',
  'IFNA2',
  'LSP1',
  'IFNA1',
  'IFNA4',
  'CEBPG',
  'CAMK2A',
  'CAMK2B',
  'TCIRG1',
  'HSPD1',
  'ITGAM',
  'EEA1',
  'MALT1',
  'MAPK9',
  'HLA-DMB',
  'MAPK8',
  'FCGR1A',
  'MRC1',
  'EP300',
  'MRC2',
  'MAPK3',
  'HLA-DPA1',
  'ITGAX',
  'IFNB1',
  'MAPK1',
  'NOS2',
  'NFYA',
  'CAMK2G',
  'BID',
  'HLA-DMA',
  'JAK1',
  'JAK2'],
 'Toxoplasmosis Homo sapiens hsa05145': ['TGFB1',
  'TGFB3',
  'TGFB2',
  'HSPA1L',
  'BAD',
  'MAPK13',
  'MAPK14',
  'MAPK11',
  'MAPK12',
  'MAPK10',
  'HSPA1A',
  'PPIF',
  'HSPA1B',
  'RELA',
  'TNF',
  'AKT3',
  'ALOX5',
  'AKT1',
  'AKT2',
  'MAP3K7',
  'HLA-DOB',
  'LDLR',
  'HLA-DOA',
  'MAP2K3',
  'HLA-DRB5',
  'NFKB1',
  'MYD88',
  'PIK3R1',
  'TRAF6',
  'BCL2L1',
  'BIRC7',
  'TAB2',
  'BIRC8',
  'TAB1',
  'HLA-DRB4',
  'BIRC2',
  'HLA-DRB3',
  'BIRC3',
  'HLA-DRB1',
  'IL12B',
  'IL12A',
  'MAP2K6',
  'IL10',
  'HSPA6',
  'LAMB4',
  'LAMB3',
  'HSPA8',
  'IL10RB',
  'IL10RA',
  'HSPA2',
  'LAMB2',
  'IRAK4',
  'LAMB1',
  'TYK2',
  'TNFRSF1A',
  'TLR2',
  'NFKBIB',
  'NFKBIA',
  'PIK3CB',
  'PIK3CA',
  'GNAO1',
  'IFNG',
  'HLA-DRA',
  'HLA-DQB1',
  'BCL2',
  'CYCS',
  'ITGA6',
  'TLR4',
  'CD40',
  'PIK3R5',
  'LAMC1',
  'LY96',
  'LAMC3',
  'PIK3R3',
  'LAMC2',
  'PIK3R2',
  'CASP8',
  'SOCS1',
  'CASP9',
  'IRAK1',
  'CASP3',
  'CCR5',
  'CIITA',
  'HLA-DQA2',
  'HLA-DQA1',
  'STAT1',
  'IFNGR1',
  'IFNGR2',
  'CHUK',
  'PDPK1',
  'STAT3',
  'IRGM',
  'XIAP',
  'HLA-DPB1',
  'CD40LG',
  'ITGB1',
  'LAMA3',
  'LAMA2',
  'LAMA5',
  'LAMA4',
  'PIK3CD',
  'LAMA1',
  'GNAI1',
  'GNAI2',
  'GNAI3',
  'PIK3CG',
  'IKBKB',
  'MAPK9',
  'HLA-DMB',
  'MAPK8',
  'MAPK3',
  'HLA-DPA1',
  'MAPK1',
  'NOS2',
  'IKBKG',
  'HLA-DMA',
  'JAK1',
  'JAK2'],
 'Leishmaniasis Homo sapiens hsa05140': ['TGFB1',
  'TGFB3',
  'TGFB2',
  'IL10',
  'JUN',
  'ITGA4',
  'IRAK4',
  'MAPK13',
  'MAPK14',
  'MAPK11',
  'IL1A',
  'TLR2',
  'NFKBIB',
  'IL1B',
  'IL4',
  'NFKBIA',
  'MAPK12',
  'FCGR2A',
  'IFNG',
  'HLA-DRA',
  'HLA-DQB1',
  'NCF1',
  'FCGR2C',
  'PTPN6',
  'TLR4',
  'RELA',
  'TNF',
  'LOC102723407',
  'FCGR3A',
  'FCGR3B',
  'IRAK1',
  'MAP3K7',
  'HLA-DOB',
  'HLA-DQA2',
  'HLA-DOA',
  'HLA-DQA1',
  'CR1',
  'MARCKSL1',
  'HLA-DRB5',
  'STAT1',
  'IFNGR1',
  'IFNGR2',
  'FOS',
  'PRKCB',
  'CYBA',
  'NFKB1',
  'MYD88',
  'TRAF6',
  'HLA-DPB1',
  'TAB2',
  'TAB1',
  'HLA-DRB4',
  'HLA-DRB3',
  'HLA-DRB1',
  'ITGB2',
  'ITGB1',
  'NCF2',
  'NCF4',
  'ITGAM',
  'ELK1',
  'PTGS2',
  'C3',
  'HLA-DMB',
  'FCGR1A',
  'MAPK3',
  'HLA-DPA1',
  'IL12B',
  'MAPK1',
  'IL12A',
  'NOS2',
  'HLA-DMA',
  'JAK1',
  'JAK2'],
 'Inflammatory bowel disease (IBD) Homo sapiens hsa05321': ['TGFB1',
  'IL4R',
  'TGFB3',
  'TGFB2',
  'IL10',
  'JUN',
  'IL13',
  'NFATC1',
  'IL18',
  'FOXP3',
  'IL2',
  'IL1A',
  'TLR2',
  'IL5',
  'IL1B',
  'IL4',
  'IL6',
  'IL23A',
  'IFNG',
  'HLA-DRA',
  'HLA-DQB1',
  'TLR5',
  'TLR4',
  'IL18R1',
  'RELA',
  'IL21R',
  'NOD2',
  'TNF',
  'IL2RG',
  'TBX21',
  'STAT6',
  'IL12RB2',
  'HLA-DOB',
  'IL12RB1',
  'HLA-DQA2',
  'HLA-DOA',
  'HLA-DQA1',
  'SMAD3',
  'SMAD2',
  'HLA-DRB5',
  'STAT1',
  'IFNGR1',
  'IFNGR2',
  'STAT3',
  'STAT4',
  'NFKB1',
  'IL17A',
  'MAF',
  'HLA-DPB1',
  'IL17F',
  'HLA-DRB4',
  'HLA-DRB3',
  'HLA-DRB1',
  'IL22',
  'IL21',
  'IL23R',
  'RORC',
  'GATA3',
  'RORA',
  'IL18RAP',
  'HLA-DMB',
  'HLA-DPA1',
  'IL12B',
  'IL12A',
  'HLA-DMA'],
 'Asthma Homo sapiens hsa05310': ['IL10',
  'HLA-DRB5',
  'IL13',
  'PRG2',
  'RNASE3',
  'IL3',
  'IL5',
  'IL4',
  'IL9',
  'HLA-DRA',
  'HLA-DQB1',
  'HLA-DPB1',
  'CD40LG',
  'HLA-DRB4',
  'MS4A2',
  'HLA-DRB3',
  'HLA-DRB1',
  'CD40',
  'CCL11',
  'TNF',
  'EPX',
  'LOC102723407',
  'HLA-DMB',
  'HLA-DPA1',
  'FCER1A',
  'FCER1G',
  'HLA-DOB',
  'HLA-DMA',
  'HLA-DQA2',
  'HLA-DOA',
  'HLA-DQA1'],
 'Intestinal immune network for IgA production Homo sapiens hsa04672': ['TGFB1',
  'AICDA',
  'CCL25',
  'IL15RA',
  'IL10',
  'HLA-DRB5',
  'IL15',
  'ITGA4',
  'TNFSF13',
  'IL2',
  'IL5',
  'IL4',
  'CXCL12',
  'IL6',
  'LTBR',
  'HLA-DRA',
  'HLA-DQB1',
  'CD28',
  'HLA-DPB1',
  'CD40LG',
  'MAP3K14',
  'HLA-DRB4',
  'HLA-DRB3',
  'CCL28',
  'HLA-DRB1',
  'CD86',
  'CD40',
  'TNFRSF13C',
  'TNFRSF13B',
  'PIGR',
  'CD80',
  'TNFSF13B',
  'LOC102723407',
  'HLA-DMB',
  'CXCR4',
  'TNFRSF17',
  'HLA-DPA1',
  'CCR9',
  'MADCAM1',
  'ITGB7',
  'HLA-DOB',
  'HLA-DMA',
  'HLA-DQA2',
  'ICOS',
  'CCR10',
  'HLA-DOA',
  'ICOSLG',
  'HLA-DQA1'],
 'Viral myocarditis Homo sapiens hsa05416': ['CAV1',
  'HLA-DRA',
  'HLA-DQB1',
  'CD28',
  'CYCS',
  'MYH6',
  'MYH7',
  'CD86',
  'CD40',
  'CD80',
  'LOC102723407',
  'ACTB',
  'CASP8',
  'CASP9',
  'CCND1',
  'CASP3',
  'DAG1',
  'HLA-DOB',
  'HLA-DQA2',
  'HLA-DOA',
  'HLA-DQA1',
  'CXADR',
  'HLA-DRB5',
  'HLA-C',
  'HLA-A',
  'HLA-B',
  'HLA-G',
  'HLA-E',
  'HLA-F',
  'EIF4G1',
  'HLA-DPB1',
  'CD40LG',
  'HLA-DRB4',
  'HLA-DRB3',
  'EIF4G3',
  'EIF4G2',
  'HLA-DRB1',
  'ITGB2',
  'LAMA2',
  'ACTG1',
  'PRF1',
  'ITGAL',
  'ICAM1',
  'SGCG',
  'SGCD',
  'HLA-DMB',
  'SGCB',
  'SGCA',
  'ABL2',
  'RAC3',
  'HLA-DPA1',
  'RAC1',
  'RAC2',
  'ABL1',
  'DMD',
  'FYN',
  'BID',
  'HLA-DMA',
  'CD55'],
 'Autoimmune thyroid disease Homo sapiens hsa05320': ['IL10',
  'IL2',
  'IL5',
  'IL4',
  'TG',
  'FAS',
  'HLA-DRA',
  'HLA-DQB1',
  'CD28',
  'CD86',
  'CD40',
  'CD80',
  'LOC102723407',
  'CTLA4',
  'HLA-DOB',
  'HLA-DQA2',
  'HLA-DOA',
  'HLA-DQA1',
  'IFNA13',
  'IFNA14',
  'HLA-DRB5',
  'IFNA16',
  'IFNA17',
  'GZMB',
  'HLA-C',
  'HLA-A',
  'HLA-B',
  'HLA-G',
  'HLA-E',
  'TSHR',
  'HLA-F',
  'HLA-DPB1',
  'CD40LG',
  'HLA-DRB4',
  'HLA-DRB3',
  'IFNA10',
  'HLA-DRB1',
  'IFNA6',
  'IFNA5',
  'IFNA8',
  'IFNA7',
  'IFNA2',
  'IFNA1',
  'IFNA4',
  'PRF1',
  'FASLG',
  'HLA-DMB',
  'TPO',
  'HLA-DPA1',
  'CGA',
  'HLA-DMA',
  'IFNA21',
  'TSHB'],
 'Allograft rejection Homo sapiens hsa05330': ['IL10',
  'HLA-DRB5',
  'GZMB',
  'HLA-C',
  'HLA-A',
  'HLA-B',
  'HLA-G',
  'HLA-E',
  'IL2',
  'HLA-F',
  'IL5',
  'IL4',
  'FAS',
  'IFNG',
  'HLA-DRA',
  'HLA-DQB1',
  'CD28',
  'HLA-DPB1',
  'CD40LG',
  'HLA-DRB4',
  'HLA-DRB3',
  'HLA-DRB1',
  'CD86',
  'CD40',
  'CD80',
  'PRF1',
  'TNF',
  'FASLG',
  'LOC102723407',
  'HLA-DMB',
  'HLA-DPA1',
  'IL12B',
  'IL12A',
  'HLA-DOB',
  'HLA-DMA',
  'HLA-DQA2',
  'HLA-DOA',
  'HLA-DQA1'],
 'Type I diabetes mellitus Homo sapiens hsa04940': ['PTPRN2',
  'HLA-DRB5',
  'GZMB',
  'GAD2',
  'GAD1',
  'HLA-C',
  'HLA-A',
  'HLA-B',
  'HLA-G',
  'HLA-E',
  'IL2',
  'HLA-F',
  'IL1A',
  'IL1B',
  'CPE',
  'FAS',
  'IFNG',
  'HLA-DRA',
  'HLA-DQB1',
  'CD28',
  'LTA',
  'HLA-DPB1',
  'HLA-DRB4',
  'HLA-DRB3',
  'HLA-DRB1',
  'CD86',
  'CD80',
  'PTPRN',
  'PRF1',
  'TNF',
  'ICA1',
  'FASLG',
  'HSPD1',
  'INS',
  'HLA-DMB',
  'HLA-DPA1',
  'IL12B',
  'IL12A',
  'HLA-DOB',
  'HLA-DMA',
  'HLA-DQA2',
  'HLA-DOA',
  'HLA-DQA1'],
 'Graft-versus-host disease Homo sapiens hsa05332': ['HLA-DRB5',
  'GZMB',
  'HLA-C',
  'KIR3DL1',
  'KIR3DL2',
  'HLA-A',
  'HLA-B',
  'HLA-G',
  'HLA-E',
  'IL2',
  'HLA-F',
  'IL1A',
  'IL1B',
  'IL6',
  'FAS',
  'IFNG',
  'HLA-DRA',
  'HLA-DQB1',
  'CD28',
  'KLRD1',
  'HLA-DPB1',
  'HLA-DRB4',
  'HLA-DRB3',

In [47]:
print("%s gene_sets used for further statistical testing....."% len(gmt))

252 gene_sets used for further statistical testing.....

In [48]:
permutation_n

1000

In [50]:
results,hit_ind,rank_ES, subsets = gsea_compute(data=dat, n=permutation_n,gmt=gmt, weighted_score_type=weighted_score_type,
                                                permutation_type=permutation_type, method=method,
                                                phenoPos=phenoPos, phenoNeg=phenoNeg, classes=classes, ascending=ascending,
                                                seed=None)
res = OrderedDict()
for gs,gseale,ind,RES in zip(subsets, list(results), hit_ind, rank_ES):        
    rdict = OrderedDict()      
    rdict['es'] = gseale[0]
    rdict['nes'] = gseale[1]
    rdict['pval'] = gseale[2]
    rdict['fdr'] = gseale[3]
    rdict['gene_set_size'] = len(gmt[gs])
    rdict['matched_size'] = len(ind)
    rdict['rank_ES'] = RES
    rdict['genes'] = dat2.ix[ind,'gene_name'].tolist()
    rdict['hit_index'] = ind
    res[gs] = rdict           

res_df = pd.DataFrame.from_dict(res,orient='index')
res_df.index.name = 'Term'
res_df.sort_values(by='fdr', inplace=True)

res_df.drop(['rank_ES','hit_index'], axis=1, inplace=True)

KeyboardInterrupt: